version: '3'
services:
  client:
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./:/app
    ports:
      - '5173:5173'
